const data = ['H@B TEAM - 8',
    '[H@B] Ayman',
    '[H@B| Luke Choi',
    '[H@B] Mason',
    '[H@B| Melvin He',
    '[H@B] Morgane feed me',
    '[H@B] Sherry',
    '[H@B] Spandan spaghetti connoisseur',
    '[H@B] Suraj',
    'Advait',
    'Aaron',
    'Albert.S',
    'Alex Khosrowshahi',
    'anyct',
    'averagetaco',
    'awoot',
    'nikki haley',
    'Ayachi',
    'Azra',
    'bananna',
    'bigboybrute',
    'bowlingpinbird',
    'Brandon',
    'Brian',
    'caitlyn',
    'Charlie',
    'chilaxan',
    'ChilledGumbo',
    'chrisc',
    'deleteduser',
    'dijonb',
    'DiveshAnchaliya',
    'DoubleJay',
    'Dylan',
    'EasyAsPai',
    'edward',
    'Elliot',
    'emem9112',
    'ERIC_EX®',
    'evon',
    'ernest chausson',
    'francis',
    'habeeba',
    'Helen Peng',
    'heliumballoon',
    'henree',
    'ilanathellama',
    'jacqkieu',
    'Jo',
    'joellations',
    'joshua phelps',
    'JTots',
    'kasen0177',
    'katie hi',
    'kay519',
    'kayzee',
    'Khan',
    'knee',
    'Krithika_b95',
    'kwang',
    'Kyro G',
    'Lilly',
    'linda',
    'louis',
    'Marc',
    'mehmetaphorically',
    'morganlo',
    'mwalsh',
    'Panda~',
    'patback000',
    'Prorex911',
    'puggle',
    'Quinn',
    'Rice',
    'rougue',
    'Saurav',
    'selena',
    'Sharwin24',
    'Shubh',
    'sophia :)',
    'spod',
    'sunny_cloud.',
    'sunnyd_isme',
    'sydney',
    'UrbanCircle66',
    'Vincent',
    'watermelonseed',
    'pigeon 目',
    'webs',
    'Worm',
    'Yutong Wang',
    'ONLINE - 4',
    'Display Name',
    'Hack@Brown',
    'BOT',
    '[H@B] Adela',
    '[H@B] Albert',
    '[H@B] Alex Hogue',
    '[H@B] Alexis',
    '[H@B] Alyssa',
    '[H@B] Andrew',
    '[H@B] corinna',
    '[H@B] Cynthia Wang',
    '[H@B] Daniel',
    '1H@B| Emily',
    '[H@B] Emily',
    '[H@B] Erin',
    '[H@BI Ethan Fry',
    '[H@B] Evan',
    '[H@B] Fabio Villatoro',
    '[H@BI Faith',
    '[H@B| Hadley',
    '[H@B| Justin Chan',
    '[H@B] Justin Shin',
    '[H@B] Kathryn',
    '[H@B] Kelly Jeong',
    '[H@B] Luke',
    '[H@B] Mindy Kim',
    '[H@B| Morgane',
    '[H@B] Nathan Phan',
    '[H@B] Nick',
    '[H@B] Olivia',
    '[H@B] Patrick',
    '[H@B] Pratham',
    '[H@B] risheetha',
    '[H@B] Sam Salseda',
    '[H@B] Sana',
    '[H@B] Sarah',
    '[H@B] Sophia',
    '[H@B] Teddy',
    '[H@B] Vivian',
    '[Mentor] Omkar',
    '[Mentor] Will',
    '[MLH] Kari',
    'A Weevil Desire',
    'A.J. Shulman',
    'aday woohoo!',
    'Albert_YH',
    'Alex',
    'Alex Ott',
    'Alexandra Hu',
    'allens',
    'Allie',
    'ally',
    'Alondra',
    'Alyssa',
    'Amber Hasan',
    'Amy',
    'angel',
    'anjana6542',
    'anzhex',
    'aqua',
    'Archestrike',
    'arianaazarbal',
    'ArigatoJaeger',
    'arjan',
    'atharva',
    'audrey',
    'avonderg.',
    'axd14',
    'azhou4587',
    'Azis',
    'bakujoe',
    'ball',
    'bananapeele',
    'beek',
    'bella<3cats',
    'brandonyan.',
    'Brendan',
    'Building',
    'camblue.123',
    'carolinec19',
    'cash',
    'catted',
    'Charlene',
    'chris_parvankin?',
    'christie',
    'christina',
    'Colin',
    'Connie',
    'Contrary Capital',
    'd1keake',
    'dan',
    'Dan Healey',
    'danielsedarous',
    'danish',
    'DavidMazur',
    'deshler',
    'Devendra Sharma',
    'Dom',
    'dz',
    'ecdhyn',
    'Eitan',
    'el mono',
    'Eleanor',
    'Emelyn',
    'emrearslan',
    'Eric',
    'erica',
    'erica5140',
    'Ethan',
    'faith',
    '；',
    'Fitz',
    'freddyryanson',
    'fruitbat',
    'grace',
    'gracecar',
    'haileyyy',
    'hannah',
    'hannah',
    'Hayz',
    'hidabeast',
    'hudaabdulla',
    'humblegranny',
    'iamsoul123',
    'Icgrus',
    'Isabella',
    'Jacob',
    'jacobh25',
    'Jaelyn',
    'Jalen',
    'Jameson',
    'jeffieboy',
    'Jeffrey',
    'JeighDowg',
    'jess',
    'jimin',
    'jjchill',
    'jkoyu',
    'jmafs',
    'Jo',
    'johannan0204',
    'John',
    'jonah',
    'JoseG',
    'JoseG',
    'josho',
    'JR Byers',
    'JRMY',
    'julia',
    'Julia',
    'Julia',
    'KaterinaN',
    'kazar4',
    'Kazen',
    'kenooth',
    'Keyan',
    'Keyan',
    'Khaotic',
    'Khoi Le',
    'kiera3473',
    'kix',
    'Knuceles',
    'krishn',
    'Krithika',
    'kshitij',
    'Lana Yang-Maccini',
    'larjboi',
    'leatysheepy',
    'Lemohns',
    'Liliana',
    'Lily',
    'lucid_789',
    'lucy_j_g',
    'm888lava',
    'M_Lee',
    'Macilee MacKenzie',
    'macq|',
    'Marcel M.S.',
    'mason',
    'Masroor',
    'mat:)',
    'max liu',
    'mazechamp',
    'mbrotinle',
    'meemat',
    'Michael',
    'mike woodilla',
    'Mikey705',
    'mikeyy',
    'mojo_jojo',
    'Mrag',
    'mumtahinamomo',
    'Mz.lilypad',
    'Nancy',
    'NaphatP',
    'Nathan',
    'nghi',
    'Nicholas Vadasz',
    'nm',
    'NoF',
    'Noor',
    'nor',
    'nora',
    'Nothingness',
    'Oscar P',
    'Parneet Sandhu',
    'pocky',
    'Preetish',
    'presidentviren',
    'Priyanka_Pande_Tea...',
    'puppy',
    'purplepennamee',
    'R1sh1',
    'Raakesh',
    'rachel',
    'rachelb',
    'ramen',
    'raphael1',
    'ravan',
    'razo',
    'ria',
    'Ria',
    'Robynn',
    'RuthUkubay',
    'Ryanhuang8',
    'ryguy',
    'räke',
    'Sana',
    'Sapphiretn',
    'sarah',
    'Saul LL.',
    'sgundotra',
    'Shivshankar Prasad',
    'Shubham Singh',
    'Shuhrat T',
    'siming',
    'sir-oof-a-lot',
    'sisquatch',
    'skellin',
    'Spod',
    'Spod',
    'Sree',
    'Srija',
    'SrijaC',
    'Suhani',
    'Superbaseball101',
    'Swayam',
    'Tas',
    'thunder_jason',
    'Tim',
    'Timothy Pyon',
    'TinyBear',
    'Tomato',
    '`UltrusBot',
    'UnorthdoxCage',
    'Varga',
    'Vicky Yang',
    'viren mehta',
    'wangmaster',
    'watermeeloon',
    'Vicky Yang',
    'viren mehta',
    'wangmaster',
    'watermeeloon',
    'WAY TOO OP',
    'Xiling Zhang',
    'ya_boi_meatball_mike',
    'yaaqub',
    'Yassin',
    'yixiangsun.',
    'Yulan Wang',
    'Zetao',
    '大帅哥',]

const locationData = [
    '195 Angell Street',
    'Alumnae Hall',
    'Applied Math Building',
    'Arnold Laboratory',
    'Barus and Holley Building',
    'Barus Hall',
    '88 Benevolent Street',
    'Biomedical Center (BMC)',
    'Blistein House',
    '68+1⁄2 Brown Street',
    '70 Brown Street',
    '59 Charlesfield Street',
    'Churchill House',
    'Corliss-Brackett House',
    'Dyer House',
    'Edward W. Kassar House',
    'Engineering Research Center',
    'Feinstein House',
    'Friedman Hall',
    'Geo-Chem Building',
    '155 George Street',
    '180 George Street',
    '182 George Street',
    'Gerard House',
    'Giddings House',
    'Gould Laboratory',
    'Grant Recital Hall',
    'Grimshaw-Gudewicz Medical Building',
    'Hirschfeld House',
    '190 Hope Street',
    'Horace Mann House',
    'Lincoln Field Building',
    'List Art Center',
    'Lyman Hall',
    'MacFarlane House',
    'Meiklejohn House',
    'W. Duncan MacMillan Hall',
    'Manning Hall',
    'Marston Hall',
    'Maxcy Hall',
    'Morrison-Gerard Studio',
    'Nelson Center for Entrepreneurship',
    'Nicholson House',
    'Norwood House',
    'Partridge Hall',
    'Pembroke Hall',
    'Lindemann Performing Arts Center',
    'Peter Green House',
    'Prospect House',
    'Prince Engineering Laboratory',
    'Rhode Island Hall',
    'Robinson Hall',
    'Rochambeau House',
    'Salomon Center',
    'Sayles Hall',
    'Sharpe House',
    '70 Ship Street',
    'Shirley Miller House',
    'Sidney E. Frank Hall for Life Sciences',
    'Smith-Buonanno Hall',
    '121 South Main Street',
    'Steinert Hall',
    'Stephen Robert Hall',
    '2 Stimson Avenue',
    'T.F. Green Hall',
    '135 Thayer Street',
    'Thomas Whitaker house',
    'Urban Environmental Lab',
    'Walter Hall',
    '70 Waterman Street',
    '131 Waterman Street',
    '133 Waterman Street',
    '137 Waterman Street',
    'Wilbour Hall',
    'Building',
    '20 Benevolent Street',
    '26 Benevolent Street',
    'Benoni Cooke House',
    'Brown Office Building',
    '8 Fones Alley',
    '25 George Street',
    'Grad Center E',
    'Hemisphere Building',
    'Maddock Alumni Center',
    'Page-Robinson Hall',
    'South Street Landing',
    'University Hall',
    'Building',
    'Annmary Brown Memorial',
    'John Carter Brown Library',
    'John D. Rockefeller Jr. Library',
    'John Hay Library',
    'Library Collections Annex',
    'Orwig Music Center',
    'Sciences Library',
    'Building',
    'Barbour Hall',
    'Barbour Hall Apartments',
    'Chen Family Hall',
    'William & Ami Danoff Hall',
    'Grad Center A',
    'Grad Center B',
    'Grad Center C',
    'Grad Center D',
    'King House',
    'Perkins Hall',
    'Young Orchard 2',
    'Young Orchard 4',
    'Young Orchard 10',
    'Vartan Gregorian Quad A',
    'Vartan Gregorian Quad B',
    'Building',
    'Archibald House',
    'Bronson House',
    'Everett House',
    'Jameson House',
    'Mead House',
    'Poland House',
    'Building',
    'Caswell Hall',
    'Hegeman Hall',
    'Hope College',
    'Littlefield Hall',
    'Minden Hall',
    'Slater Hall',
    'Building',
    'Andrews Hall',
    'Champlin Hall',
    'Emery Hall',
    'Machado House',
    'Metcalf Hall',
    'Miller Hall',
    'Morriss Hall',
    'New Pembroke #1',
    'New Pembroke #2',
    'New Pembroke #3',
    'New Pembroke #4',
    'North House',
    'Plantations House',
    '315 Thayer Street',
    'West House',
    'Woolley Hall',
    'Buxton House',
    'Chapin House',
    'Diman House',
    'Goddard House',
    'Harkness House',
    'Marcy House',
    'Olney House',
    'Sears House',
    'Wayland House',
    'Building',
    '127 Angell Street',
    '129 Angell Street',
    '22 Benevolent Street',
    '70-72 Benevolent Street',
    '74-80 Benevolent Street',
    '84 Benevolent Street',
    '86 Benevolent Street',
    '95 Benevolent Street',
    '97 Benevolent Street',
    '99 Benevolent Street',
    '247 Bowen Street',
    '251 Bowen Street',
    '277 Brook Street',
    '281-283 Brook Street',
    '93 Brown Street',
    '95 Brown Street',
    '131-133 Brown Street',
    '38 Charlesfield Street',
    '71-73 Charlesfield Street',
    '108-110 Charlesfield Street',
    '84-86 Cushing Street',
    '154 Cushing Street',
    '134 Hope Street',
    '20 Olive Street',
    '307 Thayer Street',
    '86 Waterman Street',
    'Building',
    'River House',
    'Building',
    'Andrews House',
    'Andrews Memorial Building',
    'Carrie Tower',
    'Center for the Study of Slavery and Justice',
    'Central Heat Plant',
    '75-77 Charlesfield Street',
    '37 Cooke Street',
    '200 Dyer Street',
    'Faculty Club',
    'Faunce House',
    'Fox Point Daycare Center',
    '50 John Street',
    'Gardner House',
    'Haffenreffer Barn',
    'Haffenreffer Caretaker House',
    '125 Hope St.',
    'Ladd Observatory',
    '205/215 Meeting Street',
    'Mencoff Hall',
    'Nightingale-Brown House',
    'Sharpe Refectory',
    'Building',
    'Power Street Garage',
    'Richmond Garage',
    '1 Davol Square',
    '10 Davol Square',
    '339 Eddy Street',
    '349 Eddy Street',
    '365 Eddy Street',
    '196 Richmond Street',
    '233 Richmond Street',
    '271 Thayer Street',
    '272 Thayer Street',
    '307 Thayer Street',
    '118-120 Waterman Street',
    'The Packet Building',
    'Building',
    'Brown Stadium',
    'Marston Boat House',
    'Meehan Auditorium',
    'Olney-Margolies Athletic Center',
    'Pizzitola Sports Center',
    'Ted Turner Sailing Pavilion',
    'Center for Lacrosse and Soccer',]

export const texts = [
    {
        name: "Shubh Thorat",
        texts: [
            { from: true, text: 'Pizzitola Sports Center', datetime: '2024-02-03 10:00' },
            { from: false, text: 'Are you going to the game tonight?', datetime: '2024-02-03 10:05' },
            { from: true, text: 'Yes, I am. Are you coming too?', datetime: '2024-02-03 10:07' },
            { from: false, text: 'Definitely! Let’s meet there.', datetime: '2024-02-03 10:09' },
        ],
    },
    {
        name: "Alex Johnson",
        texts: [
            { from: true, text: 'Have you finished the project?', datetime: '2024-02-02 15:30' },
            { from: false, text: 'Not yet, still working on the last part.', datetime: '2024-02-02 15:45' },
            { from: true, text: 'Need any help?', datetime: '2024-02-02 16:00' },
            { from: false, text: 'Yes, could use some assistance with the coding.', datetime: '2024-02-02 16:15' },
        ],
    },
    {
        name: "Emma Brown",
        texts: [
            { from: false, text: 'Lunch at the new Italian restaurant?', datetime: '2024-02-01 11:00' },
            { from: true, text: 'Sounds great! What time?', datetime: '2024-02-01 11:05' },
            { from: false, text: 'How about 1 PM?', datetime: '2024-02-01 11:10' },
            { from: true, text: 'Perfect, see you there!', datetime: '2024-02-01 11:15' },
        ],
    },
    {
        name: "David Smith",
        texts: [
            { from: true, text: 'Basketball game this weekend?', datetime: '2024-02-04 20:00' },
            { from: false, text: 'Can’t make it this time, got family plans.', datetime: '2024-02-04 20:10' },
            { from: true, text: 'No problem, next time then.', datetime: '2024-02-04 20:20' },
            { from: false, text: 'Definitely! Let’s plan for next weekend.', datetime: '2024-02-04 20:30' },
        ],
    },
];

export {
    data,
    locationData
}